services:
  cronos_zkevm:
    image: ghcr.io/cronos-labs/external-node:mainnet-v24.23.0
    container_name: cronos-zkevm-node
    restart: unless-stopped
    stop_grace_period: "120s"
    depends_on:
      - postgres
    environment:
      DATABASE_POOL_SIZE: 10
      DATABASE_URL: "postgresql://zksync:password@postgres:5432/zksync"
      EN_ETH_CLIENT_URL: "https://ethereum-rpc.publicnode.com"
      EN_HEALTHCHECK_PORT: 3081
      EN_HTTP_PORT: 3060
      EN_WS_PORT: 3061
      EN_PROMETHEUS_PORT: 3312
      EN_MAIN_NODE_URL: "https://seed.zkevm.cronos.org"
      EN_MERKLE_TREE_PATH: "/db/ext-node/lightweight"
      EN_STATE_CACHE_PATH: "/db/ext-node/state_keeper"
      EN_L1_BATCH_COMMIT_DATA_GENERATOR_MODE: "Validium"
      EN_L1_CHAIN_ID: 1
      EN_L2_CHAIN_ID: 388
      EN_REQ_ENTITIES_LIMIT: 1000
      EN_PRUNING_ENABLED: "false"
      RUST_LOG: "warn,zksync=info,zksync_core::metadata_calculator=debug,zksync_state=debug,zksync_utils=debug,zksync_web3_decl::client=error"
    volumes:
      - cronos_zkevm_db:/db
    ports:
      - "3060:3060"
      - "3061:3061"


  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: cronos-zkevm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zksync
      POSTGRES_USER: zksync
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_dump:/dump
    ulimits:
      nofile: 60000
      nproc: 60000
      memlock: -1

volumes:
  postgres_data:
  postgres_dump:
  cronos_zkevm_db:
