x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  postgres:
    restart: "unless-stopped"
    build:
      context: ./postgresql
      dockerfile: Dockerfile
      args:
        - DOCKER_TAG=${PG_DOCKER_TAG:-16-bookworm}
    stop_grace_period: 1m
    image: postgres:cronos-zkevm
    pull_policy: never
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-cronosdb}
      - PG_SNAPSHOT=${PG_SNAPSHOT:-https://storage.googleapis.com/cronos-zkevm-mainnet-en-pgdump/external_node.tar.gz}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 10s
      timeout: 5s
    volumes:
      - ./postgresql/load-snapshot.sh:/docker-entrypoint-initdb.d/load-snapshot.sh
      - postgres-data:/var/lib/postgresql/data/
    command: postgres ${PG_PARAMS}
    networks:
      default:
        aliases:
          - ${POSTGRES_NODE}

volumes:
  postgres-data:
